version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      YOUTUBE_API_KEY: '${YOUTUBE_API_KEY}'
      MYSQL_USER: root
      MYSQL_PASSWORD: jainxx
      MYSQL_HOST: mysql
      MYSQL_DATABASE: sequelize
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: jainxx
      MYSQL_DATABASE: sequelize
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
