tags:
- name: videos
  description: videos API

paths:
  /videos:
    get:
      description: URL to search with paginated response. By-default it will return the first page of the result based on decreasing order of the publishTime.
      summary: http://localhost/videos?search=music&page=0&size=20
      tags:
        - videos
      operationId: http://localhost/videos?search=music&page=0&size=20
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: search
          in: query
          required: false
          type: string
          description: 'optional parameter to perform search operation'
        - name: page
          in: query
          required: false
          type: integer
          format: int32
          description: 'pagination parameter'
        - name: size
          in: query
          required: false
          type: integer
          format: int32
          description: 'pagination parameter'
      responses:
        200: 
          description: '{"success":true,"totalItems":0,"videos":[],"totalPages":0,"currentPage":0}'
        500:
          description: 'Internal Server Error'
